title: Sai Srinivas Tatwik Meesala
logo: /assets/img/profiePic.jpg
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
show_ref_links: true
email: tatwik.m.19@gmail.com
linkedin: https://www.linkedin.com/in/sai-srinivas-tatwik-meesala/ 

