title: Sai Srinivas Tatwik Meesala
logo: /assets/img/profiePic.jpg
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
show_ref_links: true
email: tatwik[dot][first letter of my last name][dot]19[at]gmail[dot]com
linkedin: https://www.linkedin.com/in/sai-srinivas-tatwik-meesala/